const lang = {
  en: {
    setting: "Setting",
    theme: "Theme",
    EmailAddress: "Email Address",
    Password: "Password",
    Language: "Language",
    Notifications: "Notifications",
    ProfilePrivacy: "Profile Privacy",
    Public: "Public",
    Private: "Private",
    About: "About",
    PrivacyPolicy: "Privacy Policy",
    Licensing: "Licensing",
    Contact: "Contact",
    Searchcourses: "Search courses",
    Go: "Go",
    NoResultsFound: "No Results Found",
    AllNotes: "All Notes",
    BookMarkedNotes: "BookMarked Notes",
    FindYourNotesHere: "Find Your Notes Here",
    NoBookMarkedNotes: " No BookMarked Notes",
    Productinformation: "Product information",
    Subject: "Subject",
    Description: "Description",
    Year: "Year",
    Course: "Course",
    Likes: "Likes",
    Productoptions: "Product options",
    Download: "Download",
    First: "First",
    Prev: "Prev",
    Page: "Page",
    of: "of",
    Next: "Next",
    Last: "Last",
    Leaderboard: "Leaderboard",
    Rank: "Rank",
    ProfilePhoto: "Profile Photo",
    Username: "Username",
    Coins: "Coins",
    Notes: "Notes",
    Contribute: "Contribute",
    Requestnoteshere: "Request notes here",
    RequestPlaceholder: "I am in need of COA notes for Btech. 2nd year.....",
    Request: "Request",
    Title: "Title",
    noSubUp: "Didn't find the subject add your own",
    AddSubject: "Add",
    UploadFile: "Upload File",
    uploadPlaceholder: "COA Notes Btech. 2nd Year",
    uploadDescPlace: "Handwritten COA notes with all units complete",
    selectfile: "Please select a file to upload",
    Allowedformat: "Allowed format",
    UploadNotes: "Upload Notes",
  },
  hi: {
    setting: "सेटिंग",
    theme: "थीम",
    EmailAddress: "ई-मेल एड्रेस",
    Password: "पासवर्ड",
    Language: "भाषा",
    Notifications: "सूचनाएं",
    ProfilePrivacy: "प्रोफ़ाइल गोपनीयता",
    Public: "सार्वजनिक",
    Private: "निजी",
    Searchcourses: "कोर्स खोजें",
    About: "बारे में",
    PrivacyPolicy: "गोपनीयता नीति",
    Licensing: "लाइसेंसिंग",
    Contact: "संपर्क",
    Searchcourses: "कोर्स खोजें",
    Go: "जाएँ",
    NoResultsFound: "कोई परिणाम नहीं मिला",
    AllNotes: "सभी नोट्स",
    BookMarkedNotes: "बुकमार्क नोट्स",
    FindYourNotesHere: "अपने नोट्स यहां खोजें",
    NoBookMarkedNotes: "कोई बुकमार्क किए गए नोट नहीं",
    Productinformation: "जानकारी",
    Subject: "विषय",
    Description: "विवरण",
    Year: "वर्ष",
    Course: "कोर्स",
    Likes: "पसंद",
    Productoptions: "विकल्प",
    Download: "डाउनलोड",
    First: "पहला",
    Prev: "पिछला",
    Page: "पृष्ठ",
    of: "का",
    Next: "अगला",
    Last: "अंतिम",
    Leaderboard: "लीडरबोर्ड",
    Rank: "पद",
    ProfilePhoto: "प्रोफ़ाइल फ़ोटो",
    Username: "नाम",
    Coins: "सिक्के",
    Notes: "नोट्स",
    Contribute: "योगदान",
    Requestnoteshere: "यहां नोट्स के लिए अनुरोध करें",
    RequestPlaceholder:
      "मुझे बीटेक के द्वितीय वर्ष सीओए नोट्स की आवश्यकता है....",
    Request: "अनुरोध",
    Title: "शीर्षक",
    noSubUp: "विषय नहीं मिला अपना खुद का जोड़ें",
    AddSubject: "विषय जोड़ें",
    UploadFile: "फ़ाइल अपलोड करें",
    uploadPlaceholder: "सीओए नोट्स बीटेक दूसरा साल",
    uploadDescPlace: "सभी इकाइयों के साथ हस्तलिखित सीओए नोट्स",
    selectfile: "कृपया अपलोड करने के लिए एक फ़ाइल चुनें",
    Allowedformat: "अनुमत प्रारूप",
    UploadNotes: "नोट्स अपलोड करें",
  },
};

export default lang;
